service:
  name: pankajk-awslt-memcached

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  vpc:
    securityGroupIds:
      - ${ssm:/${env:AWSLT_BASE}/securityGroupId1}
      - ${ssm:/${env:AWSLT_BASE}/securityGroupId2}
    subnetIds:
      - ${ssm:/${env:AWSLT_BASE}/subnetId1}
      - ${ssm:/${env:AWSLT_BASE}/subnetId2}
  memcachedEndPoint: ${ssm:/${env:AWSLT_BASE}/memcached-ep}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

functions:
  memcachedGet:
    handler: src/memcached_get.get
    environment:
      memcachedEndPoint: ${self:custom.memcachedEndPoint}
    vpc: ${self:custom.vpc}
    events:
      - http:
          method: get
          path: memcached-get/{key}

  memcachedPut:
    handler: src/memcached_put.put
    environment:
      memcachedEndPoint: ${self:custom.memcachedEndPoint}
    vpc: ${self:custom.vpc}
    events:
      - http:
          method: put
          path: memcached-put/{key}

