service:
  name: pankajk-awslt-square4

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

functions:
  square4:
    handler: src/square4.square4
    events:
      - http:
          method: post
          path: square4
